feat(infer): add max_chunk_seconds option
voicepaw/so-vits-svc-fork pull request #550
Opened 2023-05-03 14:19 UTC by maximxlss

add max_chunk_seconds, option that helps split long chunks to avoid OOM

- Closes #183
- Currently simply cuts chunks into smaller pieces. Crossfade and smarter cutting might help, but it currently doesn't seem too bad.
- I have chosen a default value of 40 seconds, extrapolating my 24 gb card handling about 150 seconds to the base 6 gb. In reality it might be not the actual limit on 6 gb, needs testing.
- Could be off by default, but I think this is a fair limitation to prevent unexpected OOM errors.

2023-05-03 14:27 UTC, maximxlss commented
Sorry for the noob questions, basically my first actual feature pull request lol:

- Have just pressed some button and made this eeb7ecd. Is it okay? Should I do something?
- Checks fail cuz of formatting. Should I amend the commit or make a new one? What should be the commit message if I make a new one?

2023-05-03 14:59 UTC, 34j commented
Too perfect. I think amend is the legit way to do it, but you can do it either way. （If you don't amend, style: run pre-commit or something?)

2023-05-03 15:46 UTC, 34j requested changes

2023-05-03 15:46 UTC, 34j commented on src/so_vits_svc_fork/__main__.py
> +    "--max_chunk_seconds",
```suggestion
    "--max-chunk-seconds",
```

2023-05-04 01:01 UTC, merged

2023-05-04 01:01 UTC, 34j commented
@allcontributors add maximxlss code